package com.example.androiduidesign.utils

const val THIRTYONE = 31
const val THIRTYEIGHT = 38
const val  TWENETYFOUR = 24
const val ONE = 1
const val  ZERO = 0
const val  TWENTYSIX = 26
const val NINETEEN =19
const val  TWENTY = 20
const val TWENTYFIVE = 25
const val THIRTEEN = 13
const val THIRTYTHREE = 33
const val TWOTHOUSAND = 2000
const val ONETHOUSAND = 1000
const val SIXTHOUSAND = 6000
const val SIXTY = 60
const val TEN = 10
const val POST = "POST"
const val BASE_URL = "https://reqres.in/api/"
const val LOGIN_URL = "login"
const val SIGNUP_URL = "register"
const val EMAIL = "email"
const val PASSWORD = "password"
const val API_RESPONSE_LOG = "API Response"
const val REQRES_LOGIN_URL = "/api/login"
const val REQRES_SIGNUP_URL = "/api/register"
const val SHAREDPREF_NAME= "sharedPref"
const val SPLASHSCREEN_STATE = "SplashScreen_State"
const val LOGIN_STATE = "Login_State"
const val REMEMBER_ME = "Remember_me"